// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJVjuHYuT3pB25K2hhOY1FDEI1guAkKeg',
    appId: '1:63527896132:web:ef97b1ec6d086f5caa6811',
    messagingSenderId: '63527896132',
    projectId: 'scrap-deal-ece70',
    authDomain: 'scrap-deal-ece70.firebaseapp.com',
    storageBucket: 'scrap-deal-ece70.firebasestorage.app',
    measurementId: 'G-C5G97B0Q7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC04MSSwkOlf9GcCkM8_KyePbru_fJaoxE',
    appId: '1:63527896132:android:a6c547c5d93e94f3aa6811',
    messagingSenderId: '63527896132',
    projectId: 'scrap-deal-ece70',
    storageBucket: 'scrap-deal-ece70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOxSfW5r9MPmx-Z-bpjyBql8Pa9_V1OAE',
    appId: '1:63527896132:ios:8dd6ae4051c29139aa6811',
    messagingSenderId: '63527896132',
    projectId: 'scrap-deal-ece70',
    storageBucket: 'scrap-deal-ece70.firebasestorage.app',
    iosBundleId: 'com.example.scrapDeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOxSfW5r9MPmx-Z-bpjyBql8Pa9_V1OAE',
    appId: '1:63527896132:ios:8dd6ae4051c29139aa6811',
    messagingSenderId: '63527896132',
    projectId: 'scrap-deal-ece70',
    storageBucket: 'scrap-deal-ece70.firebasestorage.app',
    iosBundleId: 'com.example.scrapDeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJVjuHYuT3pB25K2hhOY1FDEI1guAkKeg',
    appId: '1:63527896132:web:6bb349121f6eeb25aa6811',
    messagingSenderId: '63527896132',
    projectId: 'scrap-deal-ece70',
    authDomain: 'scrap-deal-ece70.firebaseapp.com',
    storageBucket: 'scrap-deal-ece70.firebasestorage.app',
    measurementId: 'G-CVX9GSP899',
  );
}
